"""CP1404 Programming-II Assignment 2 by Vishal Manghnani

Description: This Program is an upgraded implementation of Travel Tracker 1.0.
link to Travel Tracker 1.0: https://github.com/vishmango117/CP1404-A1

The 3 main Features of the programs are as follows
1. Sort by options: List can sort by either Visited, Country or City.
2. Add New Place: Add a new place by inserting City, Country and Priority for
                  what you wish to travel, with Error checking on all inputs.
3. Generated Buttons: Each Place added has a autogenerated button
                      that for the user to mark visited or unvisited.

The Program is spread into 7 main files and they are as follows
main.py, app_gui.py, PlacesCollection.py, Places.py,
places.csv(load/save the data from/to), app_gui_layout.kv
and places_base.csv for basic data recovery"""

# importing System Libraries
from PlaceCollection import PlaceCollection
from app_gui import TravelTrackerApp


def main():

    """main(): The main function for the entire program
    which build run the GUI and builds the Place collection object"""

    # SETTING OBJECTS OF PLACECOLLECTION AND TRAVELTRACKERAPP
    myplaceobj = PlaceCollection()
    myapp = TravelTrackerApp(myplaceobj)
    myapp.run()

if __name__ == "__main__":
    main()
